platform :ios, '13.1'

target 'MHA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MHA
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RealmSwift'
  pod 'Charts'
  pod 'CalendarKit'
  pod 'AMPopTip'
  pod 'PopupDialog', '~> 1.1'

  target 'MHATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MHAUITests' do
    # Pods for testing
  end

end

